# Generated by Django 3.2.8 on 2021-10-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image',
            new_name='post',
        ),
    ]
